In [ ]:
import torch

x= torch.ones(2,3,2,2 , dtype=torch.float16)
print(x.dtype)


torch.float16


In [ ]:
x= torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
x= torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
z=x+y
print(z)
z.add_(x)
print(z)
z=torch.sub(x,y)
print(z)

tensor([[0.5718, 0.2392],
        [0.7801, 0.7291]])
tensor([[0.2891, 0.5705],
        [0.1145, 0.1167]])
tensor([[0.8609, 0.8097],
        [0.8945, 0.8458]])
tensor([[1.4327, 1.0489],
        [1.6746, 1.5749]])
tensor([[ 0.2827, -0.3313],
        [ 0.6656,  0.6124]])


In [ ]:
x= torch.rand(5,3)
print(x)
print(x[1,:])
print(x[1,1])



tensor([[0.1177, 0.7588, 0.0850],
        [0.6875, 0.5466, 0.8558],
        [0.1603, 0.8547, 0.9696],
        [0.9420, 0.6926, 0.7653],
        [0.1091, 0.6582, 0.1165]])
tensor([0.6875, 0.5466, 0.8558])
tensor(0.5466)


In [ ]:
x=torch.rand(4,4)
print(x)
y= x.view(-1,8)
print(y)
print(y.size())

tensor([[0.1534, 0.0796, 0.3177, 0.6604],
        [0.5119, 0.0758, 0.9882, 0.1768],
        [0.1184, 0.7986, 0.4057, 0.6037],
        [0.7654, 0.7306, 0.5345, 0.7166]])
tensor([[0.1534, 0.0796, 0.3177, 0.6604, 0.5119, 0.0758, 0.9882, 0.1768],
        [0.1184, 0.7986, 0.4057, 0.6037, 0.7654, 0.7306, 0.5345, 0.7166]])
torch.Size([2, 8])


In [ ]:
import numpy as np

a=torch.ones(5)
print(a)
b=a.numpy()
print(type(b))
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
a= np.ones(5)
print(a)
b= torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
  device= torch.device("cuda")
  x= torch.ones(5, device= device)
  y= torch.ones(5)
  y=y.to(device)
  z= x+y
  z = z.to("cpu")
  


In [ ]:
x= torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


In [ ]:
#AUTOGRAD

import torch

x = torch.randn(3, requires_grad= True)
print(x)
y= x+2
print(y)
z= y*y*2
z=z.mean()
print(z)

z.backward() #dz/dx
print(x.grad)


tensor([-0.7545,  0.6934,  0.2772], requires_grad=True)
tensor([1.2455, 2.6934, 2.2772], grad_fn=<AddBackward0>)
tensor(9.3279, grad_fn=<MeanBackward0>)
tensor([1.6607, 3.5913, 3.0363])


In [ ]:
#AUTOGRAD

import torch

x = torch.randn(3, requires_grad= True)
print(x)
y= x+2
print(y)
z= y*y*2
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v) #dz/dx
#print(x.grad)


tensor([ 1.4346, -0.9304, -0.7882], requires_grad=True)
tensor([3.4346, 1.0696, 1.2118], grad_fn=<AddBackward0>)
tensor([23.5928,  2.2882,  2.9371], grad_fn=<MulBackward0>)


In [ ]:
#Prevent Pytorch from tracking the gradients
x = torch.randn(3, requires_grad= True)
print(x)
x.requires_grad_(False)
print(x)
x.requires_grad_(True)
y=x.detach()
print(y)
with torch.no_grad():
  y=x+2
  print(y)

tensor([-0.3015, -0.4669, -1.2283], requires_grad=True)
tensor([-0.3015, -0.4669, -1.2283])
tensor([-0.3015, -0.4669, -1.2283])
tensor([1.6985, 1.5331, 0.7717])


In [ ]:
weights = torch.ones(4,requires_grad=True)

for epoch in range(3):
  model_output=(weights*3).sum()

  model_output.backward()
  print(weights.grad)
  weights.grad.zero_() #So as to not accumulate the values, before doing the next iteration we must empty thr gradient



tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [ ]:
weights= torch.ones(4,requires_grad=True)
optimizer = torch.optim.SGD(weights,lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: ignored