<a href="https://colab.research.google.com/github/yolitie/Deep-Learning/blob/main/SoftmaxPaBatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torchvision

dataset= torchvision.datasets.MNIST(root='./data',transform=torchvision.transforms.ToTensor())


#ON IMAGES
#CenterCrop, Grayscale, Pad, RandomAffine, RandomCrop, RandomHorizontalFlip, RandomRotation, Resize, Scale


RuntimeError: ignored

In [8]:
#SOFTMAX AND CROSS-ENTROPY
#Softmax== S(yi)=e^yi/SUMATORY(e^yi)
#the output value will be between 0 and 1, so we have probabilities.
#Let´s say we have a linear layer that has 3 output values and these values are so called scores/LOGITS
#Then the values are squashed to be between 0 and 1
#That is our prediction and then we can choose the class with the highest probability

import torch
import torch.nn as nn
import numpy as np

def softmax(x):
  return np.exp(x)/np.sum(np.exp(x),axis=0)

x=np.array([2.0,1.0,0.1])
outputs= softmax(x)
print('softmax numpy:', outputs)

x=torch.tensor([2.0,1.0,0.1])
outputs=torch.softmax(x,dim=0)
#dim=0 it computes ir along the first axis.
print(outputs)

#Lot of times the softmax function is combined with the cross-entropy function
#So this measures the performance of a classification model whose output is a probability between 0 and 1.
#It can be used in multiclass problems, the loss increases as the predicted probability diverges from the actual label,
#the better our prediction the lower our loss.

def cross_entropy(actual,predicted):
  loss= -np.sum(actual*np.log(predicted))
  return loss #/ float(predicted.shape[0])

# y must be one hot encoded
# if class 0: [1 0 0]
# if class 1: [0 1 0]
# if class 2: [0 0 1]
Y=np.array([1,0,0])

#y_pred has probabilities
Y_pred_good= np.array([0.7,0.2,0.1])
Y_pred_bad= np.array([0.1,0.3,0.6])
l1= cross_entropy(Y,Y_pred_good)
l2= cross_entropy(Y,Y_pred_bad)
print(f'Loss1 numpy: {l1:.4f}')
print(f'Loss2 numpy: {l2:.4f}')



softmax numpy: [0.65900114 0.24243297 0.09856589]
tensor([0.6590, 0.2424, 0.0986])
Loss1 numpy: 0.3567
Loss2 numpy: 2.3026


In [14]:
#DO THIS BUT IN PYTORCH

import torch
import torch.nn as nn
import numpy as np

loss= nn.CrossEntropyLoss()
#Here we have to be careful because the crossentropyloss already applies the LogSoftmax and then the negative
#log likelihood loss. so we should not implement the softmax layer for ourselves.
#Our y must not be One-Hot encoded, we shoul only put the correct class label.

Y= torch.tensor([0])
# Y has the size number of samples times the number of classes , nsamples x nclasses= 1x3
#Y_pred_good It is an array of arrays
Y_pred_good= torch.tensor([[2.0,1.0,0.1]])
Y_pred_bad= torch.tensor([[0.5,2.0,0.3]])

l1=loss(Y_pred_good,Y)
l2=loss(Y_pred_bad,Y)

print(l1.item())
print(l2.item())
#It only has one value so we can use the item() function

#How to get the predictions??
# _ because we don´t need this
_, predictions1= torch.max(Y_pred_good,1)
_, predictions2= torch.max(Y_pred_bad,1)
print(predictions1)
print(predictions2)

#loss in pytorch allows for multiple samples
#let´s increase the number of samples

#3 samples, so our actual Y has three class labels
Y= torch.tensor([2,0,1])

#Our predictions must be of size nsamples x nclasses= 3x3
Y_pred_good= torch.tensor([[0.1,1.0,2.1],[2.0,1.0,0.1],[0.1,3.0,0.1]])
Y_pred_bad= torch.tensor([[2.1,1.0,0.1],[0.1,1.0,2.1],[0.1,3.0,0.1]])

l1=loss(Y_pred_good,Y)
l2=loss(Y_pred_bad,Y)

print(l1.item())
print(l2.item())

_, predictions1=torch.max(Y_pred_good,1)
_, predictions2= torch.max(Y_pred_bad,1)
print(predictions1)
print(predictions2)



0.4170299470424652
1.840616226196289
tensor([0])
tensor([1])
0.3018244206905365
1.6241613626480103
tensor([2, 0, 1])
tensor([0, 2, 1])


In [15]:
#HOW A TYPICAL NN LOOKS LIKE
#Multiclass problem
import torch
import torch.nn as nn

class NeuralNet2(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet2,self).__init__()
    self.linear1=nn.Linear(input_size, hidden_size)
    self.relu=nn.ReLU()
    self.linear2= nn.Linear(hidden_size, num_classes)

  def forward(self,x):
    out=self.linear1(x)
    out=self.relu(out)
    out=self.linear2(out)
    #no softmax at the end
    return out

model= NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion= nn.CrossEntropyLoss() #(applies Softmax)


In [ ]:
#BINARY CLASS 
import torch 
import torch.nn as nn

#Binary classification
class NeuralNet1(nn.Module):
  def __init__(self, input_size,hidden_size):
    super(NeuralNet1,self).__init__()
    self.linear1=nn.Linear(input_size,hidden_size)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(hidden_size,1)
  
  def forward(self,x):
    out=self.linear1(x)
    out=self.relu(out)
    out=self.linear2(out)
    #sigmoid at the end
    y_pred= torch.sigmoid(out)
    return y_pred

model= NeuralNet1(input_size=28*28, hidden_size=5)
criterion= nn.BCELoss()